#obtner todos los productos
GET http://localhost:3000/productos
Accept: application/json

###

#obtener un producto por ID
GET http://localhost:3000/productos/1
Accept: application/json

###

#crear un nuevo producto
POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "Producto 1",
    "precio": 10.99,
    "id_categoria": 11,
    "id_animal": 2
} 

###

#actualizar un producto existente
PUT http://localhost:3000/productos/1
Content-Type: application/json

{
    "nombre": "Producto 1 actualizado",
    "precio": 11.99,
    "id_categoria": 1,
    "id_animal": 1
} 

###

#eliminar un producto
DELETE http://localhost:3000/productos/1
Accept: application/json



